# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  port: <%= ENV.fetch("PGPORT") { 5432 } %>

development:
  <<: *default
  database: myapp_production10

test:
  <<: *default
  database: myapp_t2

production:
  primary:
    <<: *default
    database: myapp_production10
  username: postgres
  password: password
  cache:
    <<: *default
    database: myapp_production2_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: myapp_production2_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: myapp_production2_cable
    migrations_paths: db/cable_migrate
